version: "3"
services:
  db:
    image: postgres
    restart: always
    env_file:
     - ./.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend_api
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
    - db
    volumes:
      - .:/app
    ports:
    - 3311:3311
volumes:
  pgdata: